# Generated by Django 6.0.2 on 2026-02-24 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accno', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=25)),
                ('balance', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttype', models.CharField(choices=[('deposit', 'deposit'), ('withdrawal', 'withdrawal')], max_length=15)),
                ('tamt', models.FloatField()),
                ('tdate', models.DateField()),
                ('accno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp3.account')),
            ],
        ),
    ]
